addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-debian-8
  - INSTANCE=default-fedora-latest
  - INSTANCE=default-opensuse-leap
  - INSTANCE=input-file-resource-ubuntu-1404
  - INSTANCE=input-file-resource-ubuntu-1604
  - INSTANCE=input-file-resource-centos-6
  - INSTANCE=input-file-resource-centos-7
  - INSTANCE=input-file-resource-debian-8
  - INSTANCE=input-file-resource-fedora-latest
  - INSTANCE=input-file-resource-opensuse-leap
  - INSTANCE=client-ubuntu-1404
  - INSTANCE=client-ubuntu-1604
  - INSTANCE=client-centos-6
  - INSTANCE=client-centos-7
  - INSTANCE=client-debian-8
  - INSTANCE=client-fedora-latest
  - INSTANCE=client-opensuse-leap
  - INSTANCE=server-ubuntu-1404
  - INSTANCE=server-ubuntu-1604
  - INSTANCE=server-centos-6
  - INSTANCE=server-centos-7
  - INSTANCE=server-debian-8
  - INSTANCE=server-fedora-latest
  - INSTANCE=server-opensuse-leap

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_FIPS=''
